version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/CI_CD_practice
file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu
    pattern: '**'
    owner: root
    group: root

hooks:
  AfterInstall:
    - location: scripts/after-deploy.sh
      timeout: 300
      runas: root